spring:
  datasource:
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    url: ${DB_URL_RESOURCE}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: resource-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://cloud-eureka-discovery-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true