spring:
  datasource:
    username: username
    password: password
    url: jdbc:postgresql://localhost:5432/resource_db
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
  application:
    name: resource-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true